name: Android CI

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease
