name: Build

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --no-daemon --warning-mode all

      - name: Upload
        if: github.repository == 'solodyagin/ByeByeDPIAndroid'
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/release/app-*.apk
